# Generated by Django 5.0.4 on 2024-06-15 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("eventos", "0003_participante"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Participante",
        ),
    ]
