# Generated by Django 5.0.4 on 2024-06-23 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eventos", "0005_evento_banda_alter_evento_data_alter_evento_local_and_more"),
        ("musicas", "0002_remove_musica_evento"),
    ]

    operations = [
        migrations.AddField(
            model_name="evento",
            name="musicas",
            field=models.ManyToManyField(
                blank=True, related_name="eventos", to="musicas.musica"
            ),
        ),
    ]
