# Generated by Django 5.0.6 on 2024-06-21 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('eventos', '0005_evento_banda_alter_evento_data_alter_evento_local_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Musica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('audio_link', models.URLField(blank=True, null=True)),
                ('letra_link', models.URLField(blank=True, null=True)),
                ('cifra_link', models.URLField(blank=True, null=True)),
                ('video_link', models.URLField(blank=True, null=True)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='musicas', to='eventos.evento')),
            ],
        ),
    ]
