# Generated by Django 5.0.4 on 2024-06-16 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("banda", "0002_evento"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="banda",
            name="membros",
        ),
    ]
