# Generated by Django 5.0.4 on 2024-06-17 19:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("banda", "0004_banda_membros"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="banda",
            name="membros",
            field=models.ManyToManyField(
                related_name="bandas", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
