# Generated by Django 5.0.6 on 2024-06-21 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banda', '0005_alter_banda_membros'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Evento',
        ),
    ]
