# Generated by Django 5.0.6 on 2024-06-24 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banda', '0009_alter_banda_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banda',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='media/banda/imagens/'),
        ),
    ]
